'''
Simple PV model using PVlib.
Two calc modes : Simple and detailed(future work)
    Simple: only required geo-coordinates and nominal power.

The model can run in two operations, runs once and saves output file, or shares data step by step with the main simulation.
The model uses pvlib modelchain to run the simulation, and can use either measured irradiation data, or retrieve from pvgis. 
The output is the power generated by the PV.


The model can run in two operation modes:
- Standalone mode: runs once and saves output file.
The user can either read the csv file directly into the controller, or read it with mosaik csv and plug into the simulation.
- Mosaik plug-in mode(wip): shares data step by step with the main simulation. 
Not completed, existing mosaik pv could serve as better base for this, or if possible inherit from mosaik csv.
For now, this work has been tabled to be continued in the future.

TODO:
- irradiation data column names are hardcoded, either make it flexible, or set a standard for the input data.
- implement determining the missing irradiation component, currenlty only calculates DHI from GHI and DNI.
- location list demands timezone, needed only if a radiation dataset is provided, handle this dynamically
- pvgis returs data in UTC, enforce the same standard for measured datsets as well.
'''
# %%
import pvlib
import pandas as pd
import numpy as np
import os
import json
import mosaik_api
from pvlib.pvsystem import PVSystem, Array, FixedMount
from pvlib.modelchain import ModelChain
from pvlib.location import Location
import uuid

import requests
from io import StringIO

# %%
def _define_module_inverter(nom_power, params = None):
    '''
    Select a representative PV module and inverter model from pvlib's SAM databases and define temperature model parameters for the PVSystem.

    The current implementation supports only a "simple" calculation mode:
    - A fixed module model and fixed inverter model are chosen.
    - The resulting AC power is scaled to the requested nominal power using `power_ratio`.

    Parameters
    ----------
    nom_power : float
        Requested nominal PV power for scaling (e.g., in watts).
        The reference configuration currently corresponds to ~500 W nominal.
    params : dict
        Parameter dictionary. Must contain `calc_mode`.

    Returns
    -------
    module : pandas.Series
        Module parameter set retrieved from the SAM Sandia module database.
    inverter : pandas.Series
        Inverter parameter set retrieved from the SAM CEC inverter database.
    temperature_model_parameters : dict
        Temperature model parameters for pvlib (SAPM open_rack_glass_glass).
    nSnP : list[int, int]
        [modules_per_string, strings] for the pvlib Array configuration.
    power_ratio : float
        Scaling factor applied to `mc.results.ac` to approximate `nom_power`.
    '''
    if params['calc_mode'] == 'simple':

        module_info = ['SandiaMod','SunPower_128_Cell_Module__2009__E__']
        inverter_info = ['cecinverter', 'AEconversion_GMbH__INV500_90US_xxxxx__208V_']
        nSnP = [1,1]
        power_ratio = nom_power/500 #The above config has a Pnom of 500 watts, scaling output according to user requested power.
    else:
        print('PV calc_mode not defined! NO PV for you!!!') # detailed mode has not yet been completed, refer to older models!
    # Retreiving module from db
    modules_db = pvlib.pvsystem.retrieve_sam(module_info[0])
    module = modules_db[module_info[1]] #replace BAD_CHARS = ' -.()[]:+/",' ; with simply _
    # retreiving inverter from db
    sapm_inverters = pvlib.pvsystem.retrieve_sam(inverter_info[0])
    inverter = sapm_inverters[inverter_info[1]]
    #temperature model
    temperature_model_parameters = pvlib.temperature.TEMPERATURE_MODEL_PARAMETERS['sapm']['open_rack_glass_glass']
    
    return module, inverter, temperature_model_parameters, nSnP, power_ratio

class PV():
    '''
    PV power simulator based on pvlib ModelChain.

    This class runs a one-year PV simulation at initialization time and stores the
    resulting time series in `self.weather`, including a `Power[w]` column.

    Two irradiance input modes are supported:

    1) Measured weather CSV provided by the user:
       - Reads GHI, DNI, air temperature, and wind speed.
       - Computes DHI using: DHI = GHI - DNI * cos(zenith),
         where zenith is computed via `pvlib.solarposition.get_solarposition`.
       - Runs `ModelChain.run_model(weather)`.

    2) PVGIS retrieval (if no CSV is provided):
       - Uses `pvlib.iotools.get_pvgis_hourly(..., components=True, pvcalculation=False)`
         with surface tilt/azimuth.
       - Uses plane-of-array components returned by PVGIS:
         - poa_direct
         - poa_sky_diffuse
         - poa_ground_diffuse
       - Constructs:
         - poa_diffuse = poa_sky_diffuse + poa_ground_diffuse
         - poa_global  = poa_direct + poa_diffuse
       - Runs `ModelChain.run_model_from_poa(weather)`.

    Parameters (via `params`)
    -------------------------
    coordinates : sequence
        [latitude, longitude, name, altitude, timezone]
        - timezone must be a tz database string (e.g. "UTC", "Europe/Berlin").
    nom_power : float
        Requested nominal PV power (used for scaling output in simple mode).
    calc_mode : str
        Currently only "simple" is supported.
    op_year : int, optional
        Year label used for output index (default 2023). PVGIS is capped at 2023.
    op_mode : str, optional
        "standalone" writes a CSV. "mosaik" is intended for stepwise sharing (WIP).
    irradiation_data : str, optional
        Path to measured weather CSV. If omitted, PVGIS is used.
    surface_tilt : float, optional
        Tilt angle in degrees relative to horizontal. Defaults to latitude.
    surface_azimuth : float, optional
        PVLIB azimuth convention: degrees from South (0=north, 90=east, 180 = south).
    step_size : int, optional
        Simulation step size in seconds (used by `step()`).

    Attributes
    ----------
    weather : pandas.DataFrame
        Time-indexed dataframe containing irradiance, weather, and PV power output.
        Includes `Power[w]` after initialization completes.

    Notes
    -----
    - Timezone handling is critical. pvlib requires timezone-aware indices for solar position.
      PVGIS is typically UTC. Measured datasets must be localized correctly.
    '''

    def __init__(self, params):
        '''
        Initialize the PV simulator, run the annual simulation once, and store results.

        The simulation is executed during initialization. After completion:
        - `self.weather` contains the results and the generated `Power[w]`.
        - If `op_mode == 'standalone'`, results are written to `PVlib_output.csv`.

        Parameters
        ----------
        params : dict
            See class docstring for supported keys.
        '''
        # Parameter validation
        self.validate_params(params)

        # parameters required for all calc_modes
        self.coordinates = params.get('coordinates')
        self.op_year = params.get('op_year', 2023) # To match with simulation time. PVGIS data only upto 2023.
        self.op_mode = params.get('op_mode', 'standalone') # standalone or mosaik, default to mosaik
        #parameters required for simple_calc mode
        self.nom_power = params.get('nom_power', None)
        self.calc_mode = params.get('calc_mode', None)
        ##optional 
        self.irradiation_datapath = params.get('irradiation_data', None) #Relative to this model dir
        self.surf_tilt = params.get('surface_tilt', self.coordinates[0]) # default to latitude, 
        self.surf_azimuth = params.get('surface_azimuth', 180) # default to south facing, measured from North, clockwise
        self.arrays_ = params.get('pv_arrays', [{'tilt' : self.coordinates[0], 'azimuth' : 180}]) # default to south facing, tilt = latitude
        # required if ran in standalone mode, else set by mosaik interface
        self.step_size = params.get('step_size', None)
        # Setting up for running pvlib
        # coordinates
        latitude, longitude, name, altitude, timezone = self.coordinates   #altitude here is elevation above sea level.

        self.module, self.inverter, self.temperature_model_parameters, self.nSnP, self.power_ratio = _define_module_inverter(self.nom_power, params)

        location = Location(
                latitude,
                longitude,
                name=name,
                altitude=altitude,
                tz=timezone,

            )
        # mount = FixedMount(surface_tilt=self.surf_tilt, surface_azimuth=180 - self.surf_azimuth) 

        # array = Array(
        #     mount=mount,
        #     module_parameters=self.module,
        #     temperature_model_parameters=self.temperature_model_parameters,
        #     modules_per_string=self.nSnP[0],
        #     strings=self.nSnP[1]
        # )
        array = []
        for arr in self.arrays_:
            array.append(Array(
                mount=FixedMount(surface_tilt=arr['tilt'], surface_azimuth=arr['azimuth']), 
                module_parameters=self.module,
                temperature_model_parameters=self.temperature_model_parameters,
                modules_per_string=self.nSnP[0],
                strings=self.nSnP[1]
            ))
        system = PVSystem(arrays=array, inverter_parameters=self.inverter)
        mc = ModelChain(system, location)
        
        # Irradiation data                       
        if self.irradiation_datapath: # If irradiation data available and provided
            # raw = pd.read_csv(os.path.abspath(os.path.join(os.path.dirname( __file__ ), '..', self.irradiation_datapath)), 
            #             sep=';', index_col='Time', encoding='cp1252')
            # print(f'getting irradiation data from {self.irradiation_datapath[-10:]} relative to {os.getcwd()}')
            raw = pd.read_csv(self.irradiation_datapath, sep=';', index_col='Time', encoding='cp1252')
            self.weather = pd.DataFrame({ #this is temporary, as our dataset likeso, adjust the dataset to match the standard
            'ghi' : raw['Global horizontal irradiance (W/m²)'],
            'dni' : raw['Direct normal irradiance (W/m²)'],
            'temp_air' : raw['Air temperature (°C)'],
            'wind_speed' : raw['Wind speed (m/s)']
            })
            self.weather.index = pd.to_datetime(raw.index, format = "%d.%m. %H:%M")
            self.weather.index = self.weather.index.tz_localize('UTC') # the data appears to be in UTC, making it aware, and using only UTC hereon
            #determining zenith angle to calculate dhi
            sun_pos = pvlib.solarposition.get_solarposition(self.weather.index, latitude, longitude)
            zenith = sun_pos['apparent_zenith']
            cosz = np.cos(np.radians(zenith)).clip(lower=1e-6) # 0 becomes ver small num, to avoid division by 0
            self.weather['dhi'] = self.weather["ghi"] - self.weather['dni'] * cosz  # ghi = dhi + dni.cos(zenith)
            
            
            self.weather.index = pd.to_datetime(raw.index, format = "%d.%m. %H:%M")
            self.weather.index.name=None
            self.weather = self.weather.resample('15min').interpolate(method='linear')
            
            #running the model chaing with weather data
            mc.run_model(self.weather)
        else:
            #using the method in pvlib, to retrieve POA irradiation from pvgis, using the coordinates and surface tilt/ azimuth provided by user
            # Could also get power directly, TODO: compare the two approaches; for now measured dataset vs pvgis gives comparable, 71kWh, 69 kWh respectively.

            if self.op_year > 2023:
                print(f'WARNING: PVGIS data is only available for years <= 2023, but you are using {self.op_year}.\nPVGIS will use 2023 data for you.')
                year = 2023
            else:
                year = self.op_year
         
            weather_list = fetch_pvgis(latitude, longitude, year, self.arrays_)
            self.weather = pd.DataFrame(index=weather_list[0].index) #empty df with correct index, required with fetch pvgis
            mc.run_model_from_poa(weather_list)
        
        
        self.weather['Power[w]'] = mc.results.ac * self.power_ratio /len(self.arrays_) #scaling the power, and each array will have the same power for now, TODO: consider making it more specific

        self.weather.index = self.weather.index.tz_localize(None)
        self.weather.index = self.weather.index.map(lambda x:x.replace(year = self.op_year))
        self.weather['Power[w]'] = self.weather['Power[w]'].clip(lower=0) #no negative power
        self.weather.index.name = 'Unnamed: 0' # to match the expected in VISU, and maintain compatibility with legacy PV

        unique_id = str(uuid.uuid4())[:8]
        # script_dir = os.path.dirname(os.path.abspath(__file__))
        output_dir = params.get('output_dir') 
        if not output_dir:
            raise ValueError("Missing 'output_dir' in params. The orchestrator must provide an absolute path for outputs.")
        self.output_path = os.path.join(output_dir, f'PVlib_output{unique_id}.csv')
        # self.weather.to_csv(self.output_path)
        if self.op_mode == 'standalone':
            print(f'Saving output to {os.getcwd()}/outputs/pv/PVlib_output{unique_id}.csv')
            self.weather.to_csv(self.output_path)
        # print(self.weather)
        print('PVlib simulation finished!')

    def sim(self):
        '''
        Returns output path of the generated PVlib simulation results CSV. 
        *Temporary solution: needs rethinking on logic and concept for standalone, or mosaik plug-in mode.
        For now, this method allows to read outputs with a csv reader, and plug in to des.Sim
        '''

        return self.output_path
    
    def step(self, time):
        if len(self.weather) == 0 or self.weather is None:
            print("Oops!No pv output")
        
        freq = pd.to_timedelta(self.step_size, unit="s")
        if self.step_size < 900:
            self.weather = self.weather.resample(freq).interpolate()
        elif self.step_size > 900:
            self.weather = self.weather.resample(freq).mean()

        '''Incomplete!!!
        The idea was to share the data step by step with mosaik orchestrator.
        Better idea could be to inherit/import the mosaik pv simulator, or simply the mosaik csv.
        '''

    def validate_params(self, params, *, warn: bool = True):
        """
        parameter validation for the PV model. Checks for required parameters, types, value ranges and cross-field logic.
        """
        name = type(self).__name__
        hard_errors = []
        
        rules = {
            # required for these models
            "calc_mode": {
                "required": True,
                "types": (str),
                "pred": lambda v: v in ["simple"],
                "msg": "unsupported 'calc_mode'. Supported modes: 'simple'",
            },
            "nom_power": {
                "required": True,
                "types": (int, float, np.number),
                "pred": lambda v: v > 0,
                "msg": "'nom_power' must be a number > 0 when provided.",
            },
            "coordinates": {
                "required": True,
                "types": (list, tuple),
                "pred": lambda v: len(v) == 5 and isinstance(v[0], (int, float)) and isinstance(v[1], (int, float)) and isinstance(v[2], str) and isinstance(v[3], (int, float)) and isinstance(v[4], str),
                "msg": "'coordinates' must be a list/tuple of 5 values [latitude, longitude, name, altitude, timezone] for eg. [49.1, 8.5, 'Karlsruhe', 110, 'Etc/GMT-1'].",
            },
            "op_year": {
                "required": True,
                "types": (int),
                "pred": lambda v: v > 0,
                "msg": "'op_year' must be a positive integer."
            },
            "op_mode": {
                "required": True,
                "types": (str),
                "pred": lambda v: v in ["standalone", "mosaik"],
                "msg": "'op_mode' must be either 'standalone' or 'mosaik'. mosaik mode is currently a work in progress so please use 'standalone' for now."
            },

            # optional parameters 
            "irradiation_data": {
                "required": False,
                "types": (str),
                "pred": lambda v: v.strip() != "",
                "msg": "'irradiation_data' must be a non-empty string with a relative path to the weather CSV from the project root.",
            },
            "surface_tilt": {
                "required": False,
                "types": (int, float, np.number),
                "pred": lambda v: 0 <= v <= 360,
                "msg": "'surface_tilt' must be a number between 0 and 360 degrees.",
            },
            "surface_azimuth": {
                "required": False,
                "types": (int, float, np.number),
                "pred": lambda v: 0 <= v < 360,
                "msg": "'surface_azimuth' must be a number between 0 and less than 360 degrees.",
            },
            "pv_arrays": {
                "required": False,
                "types": (list,),
                "pred": lambda v: all(isinstance(arr, dict) and 'tilt'
                    in arr and 'azimuth' in arr and isinstance(arr['tilt'], (int, float)) and isinstance(arr['azimuth'], (int, float)) for arr in v),
                "msg": "'pv_arrays' must be a list of dicts with 'tilt' and 'azimuth' as numbers, e.g. [{'tilt': 30, 'azimuth': 270}, {'tilt': 30, 'azimuth': 90}]."
            }
        }

        for key, rule in rules.items():
            required = rule.get("required", False)
            types_ = rule.get("types", None)
            pred = rule.get("pred", None)
            msg = rule.get("msg", f"Invalid '{key}'.")

            if key not in params:
                if required:
                    hard_errors.append(f"{name}: missing required parameter '{key}'.")
                continue

            val = params.get(key, None)
            if val is None:
                if required:
                    hard_errors.append(f"{name}: parameter '{key}' must not be None.")
                continue

            if types_ is not None and not isinstance(val, types_):
                hard_errors.append(f"{name}: {msg}")
                continue

            if pred is not None and not pred(val):
                hard_errors.append(f"{name}: {msg}")
        # -------------------- cross-field required logic --------------------
        expected_year = pd.Timestamp(params["sim_start"]).year
        if params["op_year"] != expected_year:
            hard_errors.append(f"{name}: op_year must match START year in main_sim ({expected_year}).")

        if hard_errors:
            raise ValueError(
                f"{name} configuration error(s):\n- " + "\n- ".join(hard_errors)
            )
        #-------------------------------------------------------------------------------

def fetch_pvgis(lat, long, year, array_configs):
    '''
    Fetches PVGIS hourly poa data for each array, and returns a list of dataframes.
    Additionally, prepares the df with necessary columns and resamples to 15 min with interpolation.
    '''
    weather_list = []
    for arr in array_configs:
        data, input, meta = pvlib.iotools.get_pvgis_hourly(
            latitude=lat,
            longitude=long,
            start=year,
            end=year,
            components=True,
            pvcalculation=False,
            outputformat='csv',
            surface_tilt=arr['tilt'],
            surface_azimuth=180 - arr['azimuth']  # PVGIS: 0=south, -90=east, +90=west
        )

        weather = data[['poa_direct', 'poa_sky_diffuse', 'poa_ground_diffuse',
                        'temp_air', 'wind_speed']].copy()

        weather['poa_diffuse'] = weather['poa_sky_diffuse'] + weather['poa_ground_diffuse']
        weather['poa_global']  = weather['poa_direct'] + weather['poa_diffuse']

        weather = weather[['poa_global', 'poa_direct', 'poa_diffuse', 'temp_air', 'wind_speed']]
        weather = weather.resample('15T', offset='10min').interpolate() #there's a 10 min offset in the timestamps of pvgis data
        weather.index = weather.index - pd.Timedelta(minutes=10)
        weather_list.append(weather)

    return weather_list

# %%

#-------------------------Mosaik Back-end-------------------------------
META = {
    'type': 'time-based',
    'models': {
        'Transformer': {
            'public': True,
            'params': ['params'],
            'attrs': ['status'],
        },
    },
}

class PVSimulator(mosaik_api.Simulator):
    def __init__(self):
        
        super().__init__(META)
        self.time_resolution = None
        self.models = dict()  # contains the model instances
        self.sid = None
        self.step_size = None
        self.eid_prefix = None
        self.time = 0
        
        
    def init(self, sid, time_resolution, step_size, params, same_time_loop=False):
        self.time_resolution = float(time_resolution)
        if self.time_resolution != 1.0:
            print('WARNING: %s got a time_resolution other than 1.0, which \
                can not be handled by this simulator.', sid)
        self.sid = sid # simulator id
        self.step_size = step_size
        if same_time_loop:
            self.meta['type'] = 'event-based'

        self.eid_prefix = params.get('eid_prefix')
        
        self.dummy_object = PV(params, warn=False)
        self.meta['models']['Transformer']['attrs'] = self.dummy_object.get_init_attrs()
        # self.meta['models']['Transformer']['trigger'] = self.dummy_object.get_init_attrs()

        return self.meta
    
    def create(self, num, model, params):
        entities = []

        next_eid = len(self.models) #if create called a second time, eid will not repeat
        for i in range(next_eid, next_eid + num):
            eid = '%s%d' % (self.eid_prefix, i)
            self.models[eid] = PV(params)
            self.models[eid].step_size = self.step_size
            entities.append({'eid': eid, 'type': model})
            
        return entities
            
    def step(self, time, inputs, max_advance):
        for eid, attrs in inputs.items():
            if self.meta['type'] == 'event-based':
                if time != self.time:
                    self.time = time
                    setattr(self.models[eid], 'step_executed', False)
            for attr, src_ids in attrs.items():
                if len(src_ids) > 1:
                    raise ValueError('Too many inputs for attribute %s' % attr)
                for val in src_ids.values():
                    setattr(self.models[eid], attr, val)

            self.models[eid].step_size = self.step_size

        for eid, model in self.models.items():
            model.step(time)

        if self.meta['type'] == 'event-based':
            return None
        else:
            return time + self.step_size
    
    def get_data(self, outputs):
        data = {}
        for eid, attrs in outputs.items():
            data[eid] = {}
            for attr in attrs:
                if attr not in self.meta['models']['Transformer'][
                        'attrs']:
                    raise ValueError('Unknown output attribute: %s' % attr)
                data['time'] = self.time
                data[eid][attr] = getattr(self.models[eid], attr)
                    
        return data

def main():
    return mosaik_api.start_simulation(PVSimulator())

if __name__ == '__main__':
    # main()
    params = {
        "calc_mode" : "simple",
        "op_year" : 2024,
        "sim_start" : "2024-01-01 00:00:00",
        "op_mode" : "standalone",
        'nom_power' : 60000, 
        'coordinates' : [48.993105744518026, 8.452778948680054, "Durlach", 115, "UTC"],
        # "irradiation_data" : "../data/inputs/2025-04-07-Project1-weather.csv"
    }

    PV(params)